theme = "rose_pine"

[editor]
line-number = "relative"
mouse = true
clipboard-provider = "wayland"
cursorline = true
continue-comments = false
auto-format = true
color-modes = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-modification-indicator", "file-name"]
right = ["version-control"]
separator = "|"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
# display-inlay-hints = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

