-- Generated by HyprMod

-- Settings
hl.config({
    animations = {
        enabled = false,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = false,
        },
        inactive_opacity = 1.0,
        rounding = 2,
        shadow = {
            enabled = false,
        },
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(813d9cff)"},
                angle = 55,
            },
        },
        gaps_in = 1,
        gaps_out = 0,
        resize_on_border = false,
    },
    input = {
        repeat_delay = 300,
        repeat_rate = 50,
    },
})

-- Bezier curves
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 3.0,
    bezier = "quick",
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "2560x1440@74.78Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = true,
})

-- Keybinds
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("uwsm app -- alacritty"))
hl.unbind("SUPER + ALT + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.unbind("SUPER + ALT + 2")
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.unbind("SUPER + ALT + 3")
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
